
$MyPlace::URLRule::Config = {
	'maps.domain'=>{
		'gangtiexia3.com'=>'site.qvod',
		'bibi138.com'=>'site.qvod.adult',
		'01aiai.com'=>'site.qvod.adult',
		'se1199.com'=>'site.qvod.adult',
		'qvod123.net'=>'site.qvod',
		'www.qvod123.net'=>'site.qvod',
		'eeuus.com'=>'site.qvod.adult',
		'wse123.com'=>'site.qvod.adult',
		'350hh.com'=>'site.qvod.adult',
		'av3030.com'=>'site.qvod.adult',
		'60se.us'=>'site.qvod.adult',
		'sss74.com'=>'site.qvod.adult',
		'zzzz35.com'=>'site.qvod.adult',
		'77soso.com'=>'site.qvod.adult',
		'tw116.com'=>'site.qvod',
		'm.weibo.cn'=>'weibo.com',
		'88dy.tv'=>"site.qvod.adult",
		'yixia.com'=>'miaopai.com',
		'miaopai.yixia.com'=>'miaopai.com',
		'ent.v.sina.cn'=>'miaopai.com',
		'btkitty.la'=>'btkitty.org',
		'btkitty.so'=>'btkitty.org',
		'bttiantang.cc'=>'bttiantang.com',
		'torrentkitty.net'=>'torrentkitty.org',
		'torrentkitty.me'=>'torrentkitty.org',
		'torrentkitty.tv'=>'torrentkitty.org',
		'67.220.90.4' =>'sexinsex.net',
		'segirlsong.com' => 'sex8.cc',
		'sxclub8.com'=>'sex8.cc',
		'btdigg.ws'=>'btdigg.me',
		'kickasstorrentsan.com','kat.cr',
	},
};

1;
