#!/usr/bin/perl -w
#http://sweeboo.com/143/great-pics-of-tiffany-taylor-playboy-playmate/
#Fri Oct 22 23:40:22 2010
use strict;



=method1
sub apply_rule {
 return (
       '#use quick parse'=>1,
       'data_exp'=>undef,
       'data_map'=>undef,
       'pass_exp'=>undef,
       'pass_map'=>undef,
       'pages_exp'=>undef,
       'pages_map'=>undef,
       'pages_pre'=>undef,
       'pages_suf'=>undef,
       'pages_start'=>undef,
       'charset'=>undef
 );
}
=cut

use MyPlace::Curl;
#use MyPlace::HTML;

sub _process {
    my ($url,$rule,$html,$propname,$exp,$rep) = @_;
    my $title = undef;
    my @data;
    my @pass_data;
    while($html =~ m/\s+$propname\s*=\s*['"]([^'"]+)['"]/ig) {
        my $value = $1;
        if($exp) {
            next unless($value =~ m/$exp/i);
            $value =~ s/$exp/$rep/gi;
        }
        push @data,$value;
    }
    #my @html = split(/\n/,$html);
    return (
        count=>scalar(@data),
        data=>[@data],
        pass_count=>scalar(@pass_data),
        pass_data=>[@pass_data],
        base=>$url,
        no_subdir=>1,
        work_dir=>$title,
    );
}

sub apply_rule {
    my $url = shift(@_);
    my $rule = shift(@_);
    if($url =~ m/http:\/\/htmlprops\/([^#]+)#([^#]*)#([^#]*)#(.+)$/) {
        my $propname = $1;
        my $exp = $2;
        my $rep = $3;
        $url = $4;
        my $http = MyPlace::Curl->new();
        $url = 'http://' . $url unless($url =~ m/^[^\/]+:/);
        my (undef,$html) = $http->get($url);
        return &_process($url,$rule,$html,$propname,$exp,$rep,@_);
    }
    return undef;
}
=cut

1;

__END__

#================================================================
# apply_rule will be called with ($RuleBase,%Rule),the result returned have these meaning:
# $result{base}          : Base url to build the full url
# $result{work_dir}      : Working directory (will be created if not exists)
# $result{data}          : Data array extracted from url,will be passed to $result{action}(see followed)
# $result{action}        : Command which the $result{data} will be piped to,can be overrided
# $result{pipeto}        : Same as action,Command which the $result{data} will be piped to,can be overrided
# $result{hook}          : Hook action,function process_data will be called
# $result{no_subdir}     : Do not create sub directories
# $result{pass_data}     : Data array which will be passed to next level of urlrule
# $result{pass_name}     : Names of each $result{pass_data}
# $result{pass_arg}      : Additional arguments to be passed to next level of urlrule
# urlrule_quick_parse($url,$rule,$data_exp,$data_map,$pass_exp,$pass_map,$charset)
# urlrule_parse_data($url,$rule,$data_exp,$data_map,$charset)
# urlrule_parse_pass_data($url,$rule,$pass_exp,$pass_map,$charset)
#================================================================

#       vim:filetype=perl
1;
