#!/usr/bin/perl -w
#http://links/
#Fri Oct 22 23:22:55 2010
use strict;


=method1
sub apply_rule {
 return (
       '#use quick parse'=>1,
       'data_exp'=>undef,
       'data_map'=>undef,
       'pass_exp'=>undef,
       'pass_map'=>undef,
       'pages_exp'=>undef,
       'pages_map'=>undef,
       'pages_pre'=>undef,
       'pages_suf'=>undef,
       'pages_start'=>undef,
       'charset'=>undef
 );
}
=cut

use MyPlace::Curl;
#use MyPlace::HTML;

sub _process {
    my ($url,$rule,$html) = @_;
    my @data;
    while($html =~ m/href\s*=\s*["']([^'"]+\.(?:jpg|png|jpeg|gif))["']/ig) {
        my $img = $1;
        $img =~ s/thumbs//g;
        $img =~ s/thumb//g;
        push @data,$1;
    }
    #my @html = split(/\n/,$html);
    return (
        count=>scalar(@data),
        data=>[@data],
        base=>$url,
        no_subdir=>1,
    );
}

sub apply_rule {
    my $url = shift(@_);
    my $rule = shift(@_);
    my $http = MyPlace::Curl->new();
    if($url =~ m/http:\/\/links\/(.+)$/) {
        $url = $1;
        $url = 'http://' . $url unless($url =~ m/^[^\/]+:/);
        my (undef,$html) = $http->get($url);
        return &_process($url,$rule,$html,@_);
    }
    return undef;
}
=cut

1;

__END__

#================================================================
# apply_rule will be called with ($RuleBase,%Rule),the result returned have these meaning:
# $result{base}          : Base url to build the full url
# $result{work_dir}      : Working directory (will be created if not exists)
# $result{data}          : Data array extracted from url,will be passed to $result{action}(see followed)
# $result{action}        : Command which the $result{data} will be piped to,can be overrided
# $result{pipeto}        : Same as action,Command which the $result{data} will be piped to,can be overrided
# $result{hook}          : Hook action,function process_data will be called
# $result{no_subdir}     : Do not create sub directories
# $result{pass_data}     : Data array which will be passed to next level of urlrule
# $result{pass_name}     : Names of each $result{pass_data}
# $result{pass_arg}      : Additional arguments to be passed to next level of urlrule
# urlrule_quick_parse($url,$rule,$data_exp,$data_map,$pass_exp,$pass_map,$charset)
# urlrule_parse_data($url,$rule,$data_exp,$data_map,$charset)
# urlrule_parse_pass_data($url,$rule,$pass_exp,$pass_map,$charset)
#================================================================

#       vim:filetype=perl
